export const locations = [
    "Johor Bahru, Johor",
    "Mersing, Johor",
    "Batu Pahat, Johor",
    "Kluang, Johor",
    "Segamat, Johor",
    "Alor Setar, Kedah",
    "Sungai Petani, Kedah",
    "Kulim, Kedah",
    "Langkawi, Kedah",
    "Kota Bharu, Kelantan",
    "Tanah Merah, Kelantan",
    "Kuala Krai, Kelantan",
    "Pasir Mas, Kelantan",
    "Melaka City, Melaka",
    "Ayer Keroh, Melaka",
    "Jasin, Melaka",
    "Seremban, Negeri Sembilan",
    "Nilai, Negeri Sembilan",
    "Port Dickson, Negeri Sembilan",
    "Kuantan, Pahang",
    "Temerloh, Pahang",
    "Bentong, Pahang",
    "Jerantut, Pahang",
    "George Town, Penang",
    "Butterworth, Penang",
    "Bayan Lepas, Penang",
    "Ipoh, Perak",
    "Taiping, Perak",
    "Manjung, Perak",
    "Batu Gajah, Perak",
    "Kangar, Perlis",
    "Padang Besar, Perlis",
    "Kota Kinabalu, Sabah",
    "Sandakan, Sabah",
    "Tawau, Sabah",
    "Lahad Datu, Sabah",
    "Kuching, Sarawak",
    "Sibu, Sarawak",
    "Miri, Sarawak",
    "Bintulu, Sarawak",
    "Shah Alam, Selangor",
    "Petaling Jaya, Selangor",
    "Subang Jaya, Selangor",
    "Klang, Selangor",
    "Kuala Terengganu, Terengganu",
    "Kemaman, Terengganu",
    "Dungun, Terengganu",
    "Kuala Lumpur",
    "Labuan",
    "Putrajaya",
];